steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'nextjs-docker .', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/savencia-cr', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/savencia-cr']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'savencia-cr', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/savencia-cr', '--region', 'europe-west1']
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/savencia-cr